version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bi-booking-app
    container_name: bi-booking-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bi_bookings
      - DB_USERNAME=bi_booking
      - DB_PASSWORD=12345687
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAIL_HOST=mailhog
      - MAIL_PORT=587
    depends_on:
      - db
      - redis
      - mailhog

  db:
    image: mysql:8.0
    container_name: bi-booking-app-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=bi_bookings
      - MYSQL_USER=bi_booking
      - MYSQL_PASSWORD=12345687
      - MYSQL_ROOT_PASSWORD=12345687
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6.0
    container_name: bi-booking-app-redis
    restart: unless-stopped
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: bi-booking-app-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
