version: "3.7"

networks:
  app-network:
    driver: bridge

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: laravel8-php-fpm-80
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes: 
      - .:/var/www
    networks: 
      - app-network
  mysql:
    image: mysql:5.7.33
    container_name: mysql
    restart: unless-stopped
    tty: true
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--explicit_defaults_for_timestamp=1']
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes: 
      - ./mysql/data:/var/lib/bibooking-sql
    networks:
      - app-network
  nginx:
    image: nginx:1.19.8-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports: 
      - 8000:80
    volumes: 
      - .:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    networks: 
      - app-network
  redis:
    image: redis:6.2.1-buster
    container_name: redis
    restart: unless-stopped
    tty: true
    volumes: 
      - ./redis/data:/data
    networks: 
      - app-network
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: unless-stopped
    ports: 
      - 8025:8025
    networks: 
      - app-network
  phpmyadmin:
    image: phpmyadmin:5.1.0-apache
    container_name: phpmyadmin
    restart: unless-stopped
    ports: 
      - 8200:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    networks:
      - app-network