version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bi-booking-app
    container_name: bi-booking-app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: mysql:latest
    container_name: bi-booking-app-db
    restart: always
    environment:
      - MYSQL_DATABASE=bi_bookings
      - MYSQL_USER=bi_booking
      - MYSQL_PASSWORD=12345687
      - MYSQL_ROOT_PASSWORD=12345687
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: bi-booking-app-redis
    restart: always

volumes:
  db_data:
